import type { Metadata } from "next";
import "./globals.css";




export const metadata: Metadata = {
  title: "Arvam Solutions",
  description: "Generated by arvam solutions",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          {children}
        </main>
      </body>
    </html>
  );
}
